#  This file is part of Ydle.
#
#    Ydle is free software: you can redistribute it and/or modify
#    it under the terms of the GNU  Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Ydle is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU  Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with Ydle.  If not, see <http://www.gnu.org/licenses/>.

################
#    Rooms     #
################
#roomData:
#    pattern:  /rooms/data/{room}/{node}/{type}
#    defaults: { _controller: YdleRoomBundle:Default:data, room:0, node:0, type:0 }
#roomAdd:
#    pattern:  /rooms/add
#    defaults: { _controller: YdleRoomBundle:Default:form }
#roomEdit:
#    pattern:  /rooms/edit/{room}
#    defaults: { _controller: YdleRoomBundle:Default:form, room:0 }
rooms:
    pattern:  /rooms
    defaults: { _controller: YdleRoomBundle:Default:index }
#roomDelete:
#    pattern:  /rooms/delete/{room}
#    defaults: { _controller: YdleRoomBundle:Default:roomdelete, room:0 } 
#roomActivation:
#    pattern:  /rooms/activation/{room}/{active}
#    defaults: { _controller: YdleRoomBundle:Default:roomactivation, room:0, active:0 } 
#room:
#    pattern:  /room/{room}
#    defaults: { _controller: YdleRoomBundle:Default:detail, room: 0 }
#room_activation:
#    pattern:  /room/{room}/{active}
#    defaults: { _controller: YdleRoomBundle:Default:detail, room: 0, active: 0 }