#  This file is part of Ydle.
#
#    Ydle is free software: you can redistribute it and/or modify
#    it under the terms of the GNU  Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Ydle is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU  Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with Ydle.  If not, see <http://www.gnu.org/licenses/>.

rooms:
  pattern:  /rooms
  defaults: { _controller: YdleRoomBundle:Default:index }
roomForm:
  pattern: /room/form/{room}
  defaults: { _controller: YdleRoomBundle:Default:roomForm, room:0 }
submitRoomForm:
  pattern: /room/form/{room}/submit
  defaults: { _controller: YdleRoomBundle:Default:submitRoomForm, room:0 }
roomDetail:
  pattern: /room/detail/{room}
  defaults: { _controller: YdleRoomBundle:Default:roomDetail, room:0 }
