<?php

namespace Ydle\RoomBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    
    public function retrieve($params = array())
    {
        $qb = $this->createQueryBuilder("r");
        $qb->where('1=1');
        $qb->orderBy('r.created_at', 'DESC');
        
        if(!empty($params['limit'])) {
            $qb->setMaxResults($params['limit']);
        }
        
        $q = $qb->getQuery();
        try {
            if(isset($params['querybuilder'])){
                return $qb;
            } else {
                return $q->getResult();
            }
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
